#!/usr/bin/python3
import sys
from math import sqrt

def print_fact(factors=[]):
    for i in range(0, len(factors)):
        print(factors[i], end="*" if i != len(factors) - 1 else "")
    print()
    return 0

with open(sys.argv[1], 'r') as file:
    for line in file:
        print(f"{line.strip()}=", end="")
        num = int(line.strip())

        res = []
        f = 2
        while f > sqrt(num):
            if num % f == 0:
                res.append(f)
                num //= f
                res.append(num)
                print_fact(res)
                break
            else:
                f += 1
